function [J, gradient] = propogate(X, y, nn_weights, input_layer_size, ...
                        hidden_layer_size,...
                        num_labels)
                    
                    
end